# ssh-addkey.yml 
---
- hosts: all
  gather_facts: no

  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"